In [14]:
import pandas as pd
arrests2 = pd.read_csv('/Users/clarissaache/Documents/Data+/SToPAGetDurhamData/cleaned_arrests_table_new.csv', low_memory=False)
arrests = pd.read_csv(
    "/Users/clarissaache/Documents/Data+/SToPAGetDurhamData/10 Clean Data/clean02.csv"
)

/Users/clarissaache/opt/miniconda3/lib/python3.9/site-packages/IPython/core/interactiveshell.py:3444: DtypeWarning: Columns (55,61,66,67,69,70,71,72,75,77) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [71]:
arrests2.loc[arrests2['narrative'].isna()]

,Unnamed: 0,agencyname,name,datetimeofarrest,file,arrestnumber,scars_tattoes_bodymarkings_etc,birthday,age,race,...,charge24IBRcode,charge24statutenumber,charge24warrantdate,charge25,charge25type,charge25counts,charge25IBRcode,charge25statutenumber,charge25warrantdate,charge4counts
0,1,Durham Police Department,"MORGAN, ALTON REGINALD",10/01/2018 10:00,00 Raw Data/data/arrests0000001.pdf,307009,NaN,02/16/1956,62.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Durham Police Department,"MURPHY, BRYCE CALEB E",03/18/2022 10:12,00 Raw Data/data/arrests0000002.pdf,329697,NaN,07/26/2001,20.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Durham Police Department,"GABRIEL, GARCIA MENDOZA",03/12/2022 00:29,00 Raw Data/data/arrests0000003.pdf,329616,NaN,10/05/2000,21.0,W,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Durham Police Department,"BROWN-ALLEN, TESHONNA LANEA",05/18/2022 00:21,00 Raw Data/data/arrests0000004.pdf,330585,NaN,05/04/1999,23.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Durham Police Department,"BILLINGS, LORENZARA",01/15/2022 09:35,00 Raw Data/data/arrests0000005.pdf,327764,NaN,07/26/1971,50.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18703,18704,Durham Police Department,"SLADE, RODERICK LESLIE",10/02/2018 09:45,00 Raw Data/data/arrests0018699.pdf,306972,NaN,03/18/1967,51.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18704,18705,Durham Police Department,"STARKS, SHOMONIQUE PORCHE",10/06/2018 14:27,00 Raw Data/data/arrests0018700.pdf,307133,NaN,02/13/1988,30.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18705,18706,Durham Police Department,"PARRISH, ANGEL LYNN",10/02/2018 09:22,00 Raw Data/data/arrests0018701.pdf,306983,NaN,06/06/1999,19.0,W,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18706,18707,Durham Police Department,"CAINE, DWIGHT GLOVER",10/06/2018 22:41,00 Raw Data/data/arrests0018702.pdf,307062,NaN,08/31/1955,63.0,B,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18707,18708,NaN,"PERKINSON, JULIE KAY",NaN,NaN,309820,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [37]:
cols1 = [
    "arrestnumber",
    "charge1",
    "charge2",
    "charge3",
    "charge4",
    "charge5",
    "charge6",
    "charge7",
    "charge8",
    "charge9",
]

# Second pages only

In [51]:
second = pd.read_csv('/Users/clarissaache/Documents/Data+/SToPAGetDurhamData/00 Raw Data/second_page_name.csv', low_memory=False)

second = second.loc[:, second.columns != "Unnamed: 0"]
second.shape

(1174, 135)

In [57]:
extra_pages = second[second.duplicated('arrestnumber')]
extra_pages.head()

,name,charge4,charge4type,charge4IBRcode,charge4statutenumber,charge4warrantdate,charge5,charge5type,charge5counts,charge5IBRcode,...,charge24warrantdate,charge25,charge25type,charge25counts,charge25IBRcode,charge25statutenumber,charge25warrantdate,arrestnumber,casenumber,charge4counts
186,"CAMPBELL, CHRISTOPHER STAPHON","B&e-vehicle, Rr Cars, Other Motor Vehicles",Fel,23F,14-56,08/01/2021,Possess Marijuana Up To 1/2 Oz,Misd,1.0,35A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325520,21025264,1
191,"WILLIAMSON, DEVONTE LAMONT",Possession Of Firearms Etc By FelonProhibited,Fel,520,14-415.1,08/02/2021,Carrying Concealed Weapons,Misd,1.0,520,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325541,21025417,1
195,"MARTIN, WANDA YVETTE",Forgery Or Possess CounterfeitInstruments,Fel,250,14-119(A),06/11/2020,Uttering A Forged Instrument,Fel,1.0,250,...,06/01/2020,Obtaining Property By False Pretenses,Fel,1.0,26A,14-100,06/01/2020,329992,20016704,1
196,"MARTIN, WANDA YVETTE",Exploit Disable Elder Trust,Fel,26A,14-112.2(B),06/01/2020,Obtaining Property By False Pretenses,Fel,1.0,26A,...,06/01/2020,Identity Theft,Fel,1.0,26F,14-113.20,06/01/2020,329992,20016704,1
226,"HIGGINS, KEIJUARN MARQUIS",Fail To Appear-release Order,Fel,90Z,15A-305(B)(2),07/27/2021,Warrant Service For Other Jurisdiction,Fel,1.0,9910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,325561,21025223,1

In [60]:
second.drop(extra_pages.index)

,name,charge4,charge4type,charge4IBRcode,charge4statutenumber,charge4warrantdate,charge5,charge5type,charge5counts,charge5IBRcode,...,charge24warrantdate,charge25,charge25type,charge25counts,charge25IBRcode,charge25statutenumber,charge25warrantdate,arrestnumber,casenumber,charge4counts
0,"ROGERS, DERRICK TYRONE",Warrant Service For Other Jurisdiction,Misd,9910,WARR,05/23/2009,Warrant Service For Other Jurisdiction,Misd,1.0,9910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327756,22001418,1
1,"SALES, JAIMOND AZAVIER",Fail To Appear-release Order,Misd,90Z,15A-305(B)(2),10/14/2021,Fail To Appear-release Order,Misd,1.0,90Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327799,22001367,1
2,"CHESSON, OGLA STELLA",Conspiracy To Commit Misdemeanor,Misd,90Z,14-2.4(B),01/11/2022,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327735,21042753,1
3,"GREEN, KEYSHAWN LAFAYETTE",Breaking And Entering Building (felony),Fel,220,14-54(A),05/05/2022,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327793,21014177,1
4,"CLARK, ERICA LATONYA",Warrant Service For Other Jurisdiction,NaN,9910,WARR,03/31/2021,Warrant Service For Other Jurisdiction,NaN,1.0,9910,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327750,22001317,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1147,"WILLIAMS, LAMARIS DEON",No Operator License,Misd,9914,20-7(A),12/29/2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309328,18045903,1
1148,"GRAVES, PRESTON DELANO III",Drive While License Revoked OrDisqualified,Misd,9914,20-28,02/08/2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309280,19005960,1
1149,"JOHNSON, CARL VINCENT",Drive While License Revoked Impaired RevBased,Misd,9914,20-28(A1),02/08/2019,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,309268,19004987,1
1166,"SHARKEY, RACHAEL MARIE",Probation Violation,Misd,90Z,15A-1345,05/15/2018,Fail To Appear-criminal Summons OrCitation,Misd,1.0,90Z,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,307039,18034601,1
1173,"COOLEY, DOMINIC QUIN",Resist Delay Obstruct Public Officer,Misd,90Z,14-223,10/06/2018,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,307075,18034662,1

In [63]:
arrests[arrests[['arrestnumber', 'casenumber']].duplicated()]

Empty DataFrame
Columns: [Unnamed: 0, agencyname, name, datetimeofarrest, file, arrestnumber, scars_tattoes_bodymarkings_etc, birthday, age, race, sex, citizenship, casenumber, skintone, height, weight, haircolor, eyecolor, armed, typeofarrest, placeofarrest, charge1, charge1type, charge1counts, charge1IBRcode, charge1statutenumber, charge1warrantdate, charge2, charge2type, charge2counts, charge2IBRcode, charge2statutenumber, charge2warrantdate, charge3, charge3type, charge3counts, charge3IBRcode, charge3statutenumber, charge3warrantdate, phonenumber, bonddateandtime, placeconfined, bondtype, bondamount, trialdate, court, arrestingofficer, releaseofficer, drugcode1, drugstatus1, drugquantity1, drugtypemeasure1, drugtype1, drugactivity1, drugcode2, drugstatus2, drugquantity2, drugtypemeasure2, drugtype2, drugactivity2, drugcode3, drugstatus3, drugquantity3, drugtypemeasure3, drugtype3, drugactivity3, drugcode4, drugstatus4, drugquantity4, drugtypemeasure4, drugtype4, drugactivity4, drugcode5, drugstatus5, drugquantity5, drugtypemeasure5, drugtype5, drugactivity5, drugcode6, drugstatus6, drugquantity6, drugtypemeasure6, drugtype6, drugactivity6, drugcode7, drugstatus7, drugquantity7, drugtypemeasure7, drugtype7, drugactivity7, drugcode8, drugstatus8, drugquantity8, drugtypemeasure8, drugtype8, drugactivity8, drugcode9, drugstatus9, drugquantity9, drugtypemeasure9, ...]
Index: []

[0 rows x 105 columns]

In [65]:
full = arrests.merge(second, on=['arrestnumber', 'casenumber'], how='left', validate='m:m')

In [66]:
print(full.shape)

(17225, 238)

In [26]:
full[full['arrestnumber']==306999][cols1]

,arrestnumber,charge1,charge2,charge3,charge4,charge5,charge6,charge7,charge8,charge9
6,306999,Assault Law Enforcement Or State Officer,Receiving Or Transferring Stolen Vehicles,Probation Violation,Probation Violation,NaN,NaN,NaN,NaN,NaN
7,306999,Assault Law Enforcement Or State Officer,Receiving Or Transferring Stolen Vehicles,Probation Violation,Probation Violation,NaN,NaN,NaN,NaN,NaN